#!/bin/bash

export TURTLEBOT_SIMULATION=0
export TURTLEBOT_OLS_SIMULATION=1
export TURTLEBOT_VISUALIZE=0
export TURTLEBOT_START_WATCHDOG_AFTER=60
export TURTLEBOT_PROFILING=0
export TURTLEBOT_STOP_AT_START=0
./rungeneric.bash

